# Title of your blog; shows in the header
name: "キオクノロンダリング"

# Description of your content (will only be used on Google Search)
description: "marksard, 3rdproject, magnetwindow"

# Your name. Will show in your footer + sidebar
author: "marksard"
lang: ja
timezone: Asia/Tokyo
encoding: utf-8

url: "http://marksard.github.io"
baseurl: ""

# A short presentation of yourself. Will show in the sidebar, under your name. Best usage would be between 30 to 50 words.
author-bio: "Joy of making, Smile be making, Interest and making."

# Social Accounts (mine, as placeholders)
github: marksard
qiita: marksard
twitter: marksard
instagram: marksardine
flickr: 95834336@N03

# Google Analytics (you may want to changes these with yours or even delete :)
ga_domain: marksard.github.io
ga_tracking_id: UA-117920855-1
google_analytics: UA-117920855-1
google_analytics_4: G-HJSBRDF8NB

# Handling Reading
exclude: ["README.md", ".gitignore", "Gemfile", "Gemfile.lock", "vendor", "art"]

# Plugins
gems: [jekyll-redirect-from, jekyll-paginate]

# Conversion
markdown: kramdown
highlighter: rouge

# Outputting
permalink: pretty
paginate: 5
paginate_path: "/page/:num"

# Markdown Processors
kramdown:
  input: GFM

# SCSS
sass:
  sass_dir: _scss
  style: :compressed

